import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const candidates = api.example.candidates.useQuery({});

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#101F34] to-[#0C1E2F]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* This heading can be replaced by the table of candidates */}
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create a <span className="mr-3 text-[#007EFF]">Hirechain</span> and
            <span className="ml-3 text-[hsl(280,100%,70%)]">T3</span> App
          </h1>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
        </div>
      </main>
    </>
  );
}
